### ISSUE TITLE
导入pmx挂了

### ISSUE THREAD

**Issue by RightFS** [AiMiDi/C4D_MMD_Tool#1]
日志和dump:
[_bugreports.zip](https://github.com/AiMiDi/C4D_MMD_Tool/files/6248485/_bugreports.zip)
模型:
[SiriusBlue200505.zip](https://github.com/AiMiDi/C4D_MMD_Tool/files/6248487/SiriusBlue200505.zip)

**Comment by AiMiDi** [comment]
已经修复，请下载最新版，你的模型有些大，导入可能需要一些时间。
