### ISSUE TITLE
Dynamic problems

### ISSUE THREAD

**Issue by wbushihenben** [AiMiDi/C4D_MMD_Tool#3]
The imported model, such as the skeleton of the skirt, has no dynamics，There is no collision information！

**Comment by AiMiDi** [comment]
I'm sorry that the plugin does not support dynamics at the moment, because MMD and C4D physics have different problems and are still looking for solutions.

**Comment by wbushihenben** [comment]
You've done a fantastic job！

**Comment by wbushihenben** [comment]
> 导入模型，比如裙子的骨架，没有动态，没有碰撞信息！

你可以手动做IK动力学！

**Comment by AiMiDi** [comment]
I have found the physics engine "Bullet" used by mmd, which can retain the characteristics of mmd physics to the greatest extent, and it is open source, and now I am trying to use it. And, which country do you live in?

我已经找到mmd使用的物理引擎“Bullet”，它可以最大程度的保留mmd物理的特性，而且它是开源的，现在已经在尝试使用它了。还有，你住在哪个国家？

**Comment by wbushihenben** [comment]
> 找到了mmd使用的物理引擎“Bullet”，可以最大程度的保留mmd物理的特性，而且是开源的，现在正在尝试使用。还有，你住在哪个国家？
> 
> 我已经找到了mmd使用的物理引擎“子弹”，它可以最大程度的保留mmd物理的特性，而且它还有很多的，现在已经在实验使用了它。，你住在哪个国家？
中国，！如果能最大程度的保留MMD物理特效，那将是非常不得了的事情。就可以不用PMX2FBX了，另外我还发现一个问题，那就是动作幅度比MMD里面的小很多。很多地方对不上
China,! If you can maximize the retention of MMD physical effects, it will be a great thing. You don't need pmx2fbx. Another problem I found is that the motion amplitude is much smaller than that in MMD. Many places are not right

**Comment by AiMiDi** [comment]
我也是中国人，请到Bilibili私信我，你说的动作偏小问题需要提供更多细节。

**Comment by wbushihenben** [comment]
我擦！国人啊！！！！！！！牛逼！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！B站ID？

**Comment by AiMiDi** [comment]
https://space.bilibili.com/30898053
